backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
collections:
  - name: 'line'
    label: 'Line'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    folder: 'content/line'
    fields:
      - label: 'stations'
        name: 'stations'
        collapsed: false
        widget: 'list'
        fields:
          - { label: 'name', name: 'name', widget: 'string' }
