backend:
  name: git-gateway
  branch: master
# publish_mode: editorial_workflow
media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
collections:
  - name: config
    label: App Config
    create: true
    slug: config
    file: 'content/config.md'
    fields:
      - { label: 'Name', name: 'name', widget: 'string', default: 'App Config' }
      - { label: 'Draw Size', name: 'size', widget: 'number', default: 150 }

  - name: 'line'
    label: 'Line'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{fields.name}}'
    folder: 'content/line'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Color', name: 'color', widget: 'string', required: false }
      - label: 'Stations'
        name: 'stations'
        collapsed: false
        widget: 'list'
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'href', name: 'href', widget: 'string', required: false }
