backend:
  name: git-gateway
  branch: master
# publish_mode: editorial_workflow
media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
collections:
  - name: configs
    label: Configs
    files:
      label: App Config
      name: app-config
      file: 'content/app-config.md'
      fields:
        - { label: 'Draw Size', name: 'size', widget: 'number', default: 150 }

  - name: 'lines'
    label: 'Lines'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{fields.name}}'
    folder: 'content/lines'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Color', name: 'color', widget: 'string', required: false }
      - label: 'Stations'
        name: 'stations'
        collapsed: false
        widget: 'list'
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'href', name: 'href', widget: 'string', required: false }
